version: '3'

services:
  app:
    build:
      context: .
      target: runner
    stdin_open: true
    tty: true
    environment: 
      # DATABASE_URL: postgres://postgres:postgres@localhost/postgres
      DATABASE_URL: sqlite:///file:/usr/app/state/db.sqlite3?uri=true
    ports: 
      - "443"
    volumes: 
      - "./app/state:/usr/app/state"
  #db:
  #  image: postgres:alpine
  #  environment: 
  #    POSTGRES_PASSWORD: postgres
