version: '3'

services:
  app:
    build:
      context: .
      target: nginx-runner
    image: tg-notify-deleted-messages-app:latest
    container_name: tg-notify-deleted-messages-app
    stdin_open: true
    tty: true
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db/postgres
      #DATABASE_URL: sqlite:///file:/usr/app/state/db.sqlite3?uri=true
      PORT: 8085
      CUSTOM_SQLALCHEMY_CONNECT_ARGS: '{"keepalives": 1, "keepalives_idle": 3, "keepalives_interval": 5, "keepalives_count": 3}'
      #CUSTOM_SQLALCHEMY_CONNECT_ARGS: '{"check_same_thread": false}'
      CUSTOM_SQLALCHEMY_CREATE_ENGINE_ARGS: '{"pool_size": 10, "max_overflow": 2, "pool_recycle": 300, "pool_pre_ping": true, "pool_use_lifo": true}'
      #GUNICORN_CMD_ARGS: "--timeout 120"
      #PYPY_GC_MAX: "250MB"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8085"
    volumes: 
      - "./app/state:/usr/app/state"
  db:
    image: postgres:alpine
    environment: 
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./app/db_state:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
